/**
 * Catalog seed configuration.
 *
 * IMPORTANT — these are configuration placeholders, not claims:
 * - Every provider is seeded DISABLED with integration mode BYOK. An admin must review the
 *   provider's commercial terms (or a signed reseller agreement) before switching to a
 *   platform-funded mode and setting `resaleVerified`.
 * - Every model is seeded with verificationStatus NEEDS_REVIEW and no license assertion.
 *   License, commercial-use and resale rights must be verified by an admin.
 * - No provider prices are seeded. Prices are entered by an admin from the provider's
 *   current price list (pricingSource) and then shown publicly. We never guess prices.
 * - Context lengths are only filled in where they are long-established public facts; the
 *   admin verifies them alongside pricing.
 */

export type SeedProvider = {
  slug: string;
  name: string;
  description: string;
  websiteUrl: string;
  adapter: "OPENAI_COMPATIBLE" | "ANTHROPIC" | "LITELLM" | "MOCK";
  baseUrl: string;
  credentialRef: string | null;
  integrationMode:
    | "DIRECT_RESALE"
    | "AUTHORIZED_RESELLER"
    | "BYOK"
    | "CUSTOM_ENTERPRISE"
    | "SELF_HOSTED"
    | "OPEN_WEIGHT";
  termsUrl?: string;
  termsNotes?: string;
  supportedEndpoints: string[];
  priority: number;
  byokSupported?: boolean;
};

export const PROVIDERS: SeedProvider[] = [
  {
    slug: "openai",
    name: "OpenAI",
    description: "GPT and embedding models via the OpenAI API.",
    websiteUrl: "https://openai.com",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.openai.com/v1",
    credentialRef: "env:OPENAI_API_KEY",
    integrationMode: "BYOK",
    termsUrl: "https://openai.com/policies/",
    termsNotes: "Platform-funded resale requires a reviewed agreement. Defaults to BYOK.",
    supportedEndpoints: ["chat", "embeddings", "images", "responses"],
    priority: 10,
  },
  {
    slug: "anthropic",
    name: "Anthropic",
    description: "Claude models via the Anthropic Messages API.",
    websiteUrl: "https://www.anthropic.com",
    adapter: "ANTHROPIC",
    baseUrl: "https://api.anthropic.com",
    credentialRef: "env:ANTHROPIC_API_KEY",
    integrationMode: "BYOK",
    termsUrl: "https://www.anthropic.com/legal/commercial-terms",
    termsNotes: "Platform-funded resale requires a reviewed agreement. Defaults to BYOK.",
    supportedEndpoints: ["chat"],
    priority: 10,
  },
  {
    slug: "google",
    name: "Google AI (Gemini API)",
    description: "Gemini models through Google's OpenAI-compatible endpoint.",
    websiteUrl: "https://ai.google.dev",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    credentialRef: "env:GOOGLE_API_KEY",
    integrationMode: "BYOK",
    termsUrl: "https://ai.google.dev/gemini-api/terms",
    supportedEndpoints: ["chat", "embeddings"],
    priority: 10,
  },
  {
    slug: "xai",
    name: "xAI",
    description: "Grok models via the xAI API.",
    websiteUrl: "https://x.ai",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.x.ai/v1",
    credentialRef: "env:XAI_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat"],
    priority: 20,
  },
  {
    slug: "mistral",
    name: "Mistral AI",
    description: "Mistral models via La Plateforme.",
    websiteUrl: "https://mistral.ai",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.mistral.ai/v1",
    credentialRef: "env:MISTRAL_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat", "embeddings"],
    priority: 20,
  },
  {
    slug: "deepseek",
    name: "DeepSeek",
    description: "DeepSeek chat and reasoning models via the DeepSeek API.",
    websiteUrl: "https://www.deepseek.com",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.deepseek.com/v1",
    credentialRef: "env:DEEPSEEK_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat"],
    priority: 20,
  },
  {
    slug: "qwen",
    name: "Alibaba Cloud Model Studio (Qwen)",
    description: "Qwen models via DashScope's OpenAI-compatible mode.",
    websiteUrl: "https://www.alibabacloud.com/product/modelstudio",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    credentialRef: "env:DASHSCOPE_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat", "embeddings"],
    priority: 20,
  },
  {
    slug: "zai",
    name: "Z.ai (GLM)",
    description: "GLM models via the Z.ai platform.",
    websiteUrl: "https://z.ai",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.z.ai/api/paas/v4",
    credentialRef: "env:ZAI_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat"],
    priority: 20,
  },
  {
    slug: "groq",
    name: "Groq",
    description: "Low-latency inference for open-weight models.",
    websiteUrl: "https://groq.com",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.groq.com/openai/v1",
    credentialRef: "env:GROQ_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat"],
    priority: 30,
  },
  {
    slug: "together",
    name: "Together AI",
    description: "Hosted inference for open-weight models.",
    websiteUrl: "https://www.together.ai",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.together.xyz/v1",
    credentialRef: "env:TOGETHER_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat", "embeddings", "images"],
    priority: 30,
  },
  {
    slug: "fireworks",
    name: "Fireworks AI",
    description: "Hosted inference for open-weight models.",
    websiteUrl: "https://fireworks.ai",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    credentialRef: "env:FIREWORKS_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat", "embeddings"],
    priority: 30,
  },
  {
    slug: "cerebras",
    name: "Cerebras",
    description: "Wafer-scale inference for open-weight models.",
    websiteUrl: "https://www.cerebras.ai",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.cerebras.ai/v1",
    credentialRef: "env:CEREBRAS_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat"],
    priority: 30,
  },
  {
    slug: "huggingface",
    name: "Hugging Face Inference Providers",
    description: "Open models via the Hugging Face router.",
    websiteUrl: "https://huggingface.co",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://router.huggingface.co/v1",
    credentialRef: "env:HF_TOKEN",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat"],
    priority: 40,
  },
  {
    slug: "cohere",
    name: "Cohere",
    description: "Cohere models via the compatibility API.",
    websiteUrl: "https://cohere.com",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://api.cohere.ai/compatibility/v1",
    credentialRef: "env:COHERE_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat", "embeddings"],
    priority: 40,
  },
  {
    slug: "openrouter",
    name: "OpenRouter",
    description: "Upstream aggregator, usable with your own OpenRouter key.",
    websiteUrl: "https://openrouter.ai",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "https://openrouter.ai/api/v1",
    credentialRef: "env:OPENROUTER_API_KEY",
    integrationMode: "BYOK",
    supportedEndpoints: ["chat"],
    priority: 90,
  },
  {
    slug: "litellm",
    name: "LiteLLM Gateway",
    description:
      "Self-hosted LiteLLM proxy for providers that need non-OpenAI auth (AWS Bedrock, Azure AI, Vertex AI).",
    websiteUrl: "https://docs.litellm.ai",
    adapter: "LITELLM",
    baseUrl: "http://litellm:4000/v1",
    credentialRef: "env:LITELLM_MASTER_KEY",
    integrationMode: "BYOK",
    termsNotes:
      "The integration mode must reflect the upstream provider configured in LiteLLM. Upstream terms apply.",
    supportedEndpoints: ["chat", "embeddings"],
    priority: 50,
    byokSupported: false,
  },
  {
    slug: "vllm",
    name: "INRENT self-hosted (vLLM)",
    description: "Open-weight models served by INRENT-operated vLLM endpoints.",
    websiteUrl: "https://docs.vllm.ai",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "http://vllm:8000/v1",
    credentialRef: "env:VLLM_API_KEY",
    integrationMode: "SELF_HOSTED",
    termsNotes: "Model weight licenses must be verified per model before platform-funded serving.",
    supportedEndpoints: ["chat", "embeddings"],
    priority: 5,
    byokSupported: false,
  },
  {
    slug: "ollama",
    name: "Ollama (local)",
    description: "Local development inference through Ollama's OpenAI-compatible API.",
    websiteUrl: "https://ollama.com",
    adapter: "OPENAI_COMPATIBLE",
    baseUrl: "http://localhost:11434/v1",
    credentialRef: null,
    integrationMode: "SELF_HOSTED",
    supportedEndpoints: ["chat", "embeddings"],
    priority: 60,
    byokSupported: false,
  },
];

export type SeedModel = {
  slug: string;
  displayName: string;
  vendor: string;
  family?: string;
  description: string;
  modalitiesIn: string[];
  modalitiesOut: string[];
  capabilities: string[];
  contextLength?: number;
  openWeights?: boolean;
  documentationUrl?: string;
  featured?: boolean;
  qualityTier?: number;
  endpoints: Array<{
    provider: string;
    providerModelId: string;
    supportsTools?: boolean;
    supportsJsonMode?: boolean;
    supportsStructuredOutput?: boolean;
    supportsVision?: boolean;
    pricingSource?: string;
  }>;
};

export const MODELS: SeedModel[] = [
  {
    slug: "openai/gpt-4.1",
    displayName: "GPT-4.1",
    vendor: "openai",
    family: "gpt-4.1",
    description: "OpenAI general-purpose model for coding, instruction following and long context.",
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "coding", "tools", "structured_output", "json_mode", "streaming", "vision"],
    documentationUrl: "https://platform.openai.com/docs/models",
    featured: true,
    qualityTier: 4,
    endpoints: [
      {
        provider: "openai",
        providerModelId: "gpt-4.1",
        supportsTools: true,
        supportsJsonMode: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        pricingSource: "https://openai.com/api/pricing/",
      },
    ],
  },
  {
    slug: "openai/gpt-4o-mini",
    displayName: "GPT-4o mini",
    vendor: "openai",
    family: "gpt-4o",
    description: "Small, fast OpenAI model for high-volume tasks.",
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "tools", "structured_output", "json_mode", "streaming", "vision"],
    contextLength: 128000,
    documentationUrl: "https://platform.openai.com/docs/models",
    featured: true,
    qualityTier: 2,
    endpoints: [
      {
        provider: "openai",
        providerModelId: "gpt-4o-mini",
        supportsTools: true,
        supportsJsonMode: true,
        supportsStructuredOutput: true,
        supportsVision: true,
        pricingSource: "https://openai.com/api/pricing/",
      },
    ],
  },
  {
    slug: "openai/text-embedding-3-small",
    displayName: "text-embedding-3-small",
    vendor: "openai",
    family: "embeddings",
    description: "OpenAI embedding model for search, clustering and retrieval.",
    modalitiesIn: ["text"],
    modalitiesOut: ["embedding"],
    capabilities: ["embedding"],
    documentationUrl: "https://platform.openai.com/docs/guides/embeddings",
    qualityTier: 2,
    endpoints: [
      {
        provider: "openai",
        providerModelId: "text-embedding-3-small",
        pricingSource: "https://openai.com/api/pricing/",
      },
    ],
  },
  {
    slug: "anthropic/claude-sonnet-4",
    displayName: "Claude Sonnet 4",
    vendor: "anthropic",
    family: "claude-4",
    description: "Anthropic model balancing intelligence and speed for coding and agents.",
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "reasoning", "coding", "tools", "streaming", "vision"],
    contextLength: 200000,
    documentationUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
    featured: true,
    qualityTier: 5,
    endpoints: [
      {
        provider: "anthropic",
        providerModelId: "claude-sonnet-4-20250514",
        supportsTools: true,
        supportsVision: true,
        pricingSource: "https://www.anthropic.com/pricing#api",
      },
    ],
  },
  {
    slug: "anthropic/claude-3.5-haiku",
    displayName: "Claude 3.5 Haiku",
    vendor: "anthropic",
    family: "claude-3.5",
    description: "Fast Anthropic model for lightweight, latency-sensitive workloads.",
    modalitiesIn: ["text"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "tools", "streaming"],
    contextLength: 200000,
    documentationUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
    qualityTier: 2,
    endpoints: [
      {
        provider: "anthropic",
        providerModelId: "claude-3-5-haiku-20241022",
        supportsTools: true,
        pricingSource: "https://www.anthropic.com/pricing#api",
      },
    ],
  },
  {
    slug: "google/gemini-2.5-flash",
    displayName: "Gemini 2.5 Flash",
    vendor: "google",
    family: "gemini-2.5",
    description: "Google's fast multimodal model with long context and thinking support.",
    modalitiesIn: ["text", "image", "audio", "video"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "reasoning", "tools", "json_mode", "streaming", "vision"],
    documentationUrl: "https://ai.google.dev/gemini-api/docs/models",
    featured: true,
    qualityTier: 3,
    endpoints: [
      {
        provider: "google",
        providerModelId: "gemini-2.5-flash",
        supportsTools: true,
        supportsJsonMode: true,
        supportsVision: true,
        pricingSource: "https://ai.google.dev/gemini-api/docs/pricing",
      },
    ],
  },
  {
    slug: "deepseek/deepseek-chat",
    displayName: "DeepSeek Chat",
    vendor: "deepseek",
    family: "deepseek",
    description: "DeepSeek's general chat model served from the DeepSeek API.",
    modalitiesIn: ["text"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "coding", "tools", "json_mode", "streaming"],
    documentationUrl: "https://api-docs.deepseek.com",
    featured: true,
    qualityTier: 3,
    endpoints: [
      {
        provider: "deepseek",
        providerModelId: "deepseek-chat",
        supportsTools: true,
        supportsJsonMode: true,
        pricingSource: "https://api-docs.deepseek.com/quick_start/pricing",
      },
    ],
  },
  {
    slug: "deepseek/deepseek-reasoner",
    displayName: "DeepSeek Reasoner",
    vendor: "deepseek",
    family: "deepseek",
    description: "DeepSeek reasoning model with visible chain-of-thought output.",
    modalitiesIn: ["text"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "reasoning", "coding", "streaming"],
    documentationUrl: "https://api-docs.deepseek.com",
    qualityTier: 4,
    endpoints: [
      {
        provider: "deepseek",
        providerModelId: "deepseek-reasoner",
        pricingSource: "https://api-docs.deepseek.com/quick_start/pricing",
      },
    ],
  },
  {
    slug: "qwen/qwen3-32b",
    displayName: "Qwen3 32B",
    vendor: "qwen",
    family: "qwen3",
    description: "Dense Qwen3 model with hybrid thinking modes. Open weights.",
    modalitiesIn: ["text"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "reasoning", "coding", "tools", "streaming"],
    openWeights: true,
    documentationUrl: "https://huggingface.co/Qwen",
    featured: true,
    qualityTier: 3,
    endpoints: [
      { provider: "qwen", providerModelId: "qwen3-32b", supportsTools: true },
      { provider: "groq", providerModelId: "qwen/qwen3-32b", supportsTools: true },
      { provider: "vllm", providerModelId: "Qwen/Qwen3-32B", supportsTools: true },
    ],
  },
  {
    slug: "qwen/qwen3.8-27b",
    displayName: "Qwen3.8 27B",
    vendor: "qwen",
    family: "qwen3.8",
    description:
      "Dense 27B vision-language model with hybrid attention. Open weights; candidate for INRENT self-hosting.",
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "reasoning", "coding", "tools", "streaming", "vision"],
    openWeights: true,
    documentationUrl: "https://huggingface.co/Qwen",
    qualityTier: 3,
    endpoints: [{ provider: "vllm", providerModelId: "Qwen/Qwen3.8-27B", supportsTools: true, supportsVision: true }],
  },
  {
    slug: "zai/glm-4.5",
    displayName: "GLM-4.5",
    vendor: "zai",
    family: "glm",
    description: "Z.ai mixture-of-experts model for agentic, reasoning and coding tasks. Open weights.",
    modalitiesIn: ["text"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "reasoning", "coding", "tools", "streaming"],
    openWeights: true,
    documentationUrl: "https://docs.z.ai",
    featured: true,
    qualityTier: 4,
    endpoints: [
      { provider: "zai", providerModelId: "glm-4.5", supportsTools: true },
      { provider: "together", providerModelId: "zai-org/GLM-4.5-Air-FP8", supportsTools: true },
    ],
  },
  {
    slug: "zai/glm-5.2",
    displayName: "GLM 5.2",
    vendor: "zai",
    family: "glm",
    description:
      "Large mixture-of-experts GLM model for agentic reasoning, coding and tool use. Open weights; requires multi-GPU serving.",
    modalitiesIn: ["text"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "reasoning", "coding", "tools", "streaming"],
    openWeights: true,
    documentationUrl: "https://docs.z.ai",
    qualityTier: 5,
    endpoints: [
      { provider: "zai", providerModelId: "glm-5.2", supportsTools: true },
      { provider: "vllm", providerModelId: "zai-org/GLM-5.2", supportsTools: true },
    ],
  },
  {
    slug: "mistral/mistral-large",
    displayName: "Mistral Large",
    vendor: "mistral",
    family: "mistral-large",
    description: "Mistral's flagship model for complex reasoning and multilingual tasks.",
    modalitiesIn: ["text"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "coding", "tools", "json_mode", "streaming"],
    documentationUrl: "https://docs.mistral.ai/getting-started/models/",
    qualityTier: 4,
    endpoints: [
      {
        provider: "mistral",
        providerModelId: "mistral-large-latest",
        supportsTools: true,
        supportsJsonMode: true,
        pricingSource: "https://mistral.ai/pricing",
      },
    ],
  },
  {
    slug: "meta/llama-3.3-70b-instruct",
    displayName: "Llama 3.3 70B Instruct",
    vendor: "meta",
    family: "llama-3.3",
    description: "Meta's 70B instruction-tuned model. Open weights under the Llama community license.",
    modalitiesIn: ["text"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "coding", "tools", "streaming"],
    openWeights: true,
    documentationUrl: "https://www.llama.com",
    featured: true,
    qualityTier: 3,
    endpoints: [
      { provider: "groq", providerModelId: "llama-3.3-70b-versatile", supportsTools: true },
      { provider: "together", providerModelId: "meta-llama/Llama-3.3-70B-Instruct-Turbo", supportsTools: true },
      { provider: "fireworks", providerModelId: "accounts/fireworks/models/llama-v3p3-70b-instruct", supportsTools: true },
      { provider: "cerebras", providerModelId: "llama-3.3-70b", supportsTools: true },
    ],
  },
  {
    slug: "xai/grok-3",
    displayName: "Grok 3",
    vendor: "xai",
    family: "grok",
    description: "xAI's general model for reasoning, coding and knowledge tasks.",
    modalitiesIn: ["text"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "reasoning", "tools", "streaming"],
    documentationUrl: "https://docs.x.ai/docs/models",
    qualityTier: 4,
    endpoints: [{ provider: "xai", providerModelId: "grok-3", supportsTools: true }],
  },
  {
    slug: "moonshotai/kimi-k3",
    displayName: "Kimi K3",
    vendor: "moonshotai",
    family: "kimi",
    description:
      "Very large multimodal mixture-of-experts model from Moonshot AI. Candidate for future multi-GPU self-hosting.",
    modalitiesIn: ["text", "image"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "reasoning", "coding", "tools", "streaming", "vision"],
    openWeights: true,
    documentationUrl: "https://huggingface.co/moonshotai",
    qualityTier: 5,
    endpoints: [{ provider: "vllm", providerModelId: "moonshotai/Kimi-K3", supportsTools: true, supportsVision: true }],
  },
  {
    slug: "google/gemma-4-12b-it",
    displayName: "Gemma 4 12B IT",
    vendor: "google",
    family: "gemma-4",
    description: "Open multimodal Gemma model with text, image and audio input. Candidate for self-hosting.",
    modalitiesIn: ["text", "image", "audio"],
    modalitiesOut: ["text"],
    capabilities: ["chat", "streaming", "vision"],
    openWeights: true,
    documentationUrl: "https://ai.google.dev/gemma",
    qualityTier: 2,
    endpoints: [{ provider: "vllm", providerModelId: "google/gemma-4-12b-it", supportsVision: true }],
  },
];

export const PLANS = [
  {
    slug: "free",
    name: "Free",
    description: "Explore the API and the playground.",
    priceMonthlyCents: 0,
    isPayAsYouGo: false,
    rpmLimit: 20,
    tpmLimit: 40_000,
    maxProjects: 2,
    maxMembers: 1,
    logRetentionDays: 7,
    features: [
      "Access to enabled catalog models",
      "Bring your own provider keys",
      "Playground",
      "7-day request log retention",
      "Community support",
    ],
    sortOrder: 0,
  },
  {
    slug: "developer",
    name: "Developer",
    description: "Pay as you go. No monthly commitment.",
    priceMonthlyCents: 0,
    isPayAsYouGo: true,
    rpmLimit: 120,
    tpmLimit: 400_000,
    maxProjects: 10,
    maxMembers: 1,
    logRetentionDays: 30,
    features: [
      "Prepaid credits — pay only for usage",
      "Higher rate limits",
      "Unlimited API keys with per-key limits",
      "Usage analytics and request logs",
      "Webhooks",
    ],
    highlighted: true,
    sortOrder: 1,
  },
  {
    slug: "pro",
    name: "Pro",
    description: "Higher limits and priority routing for production apps.",
    priceMonthlyCents: null,
    isPayAsYouGo: true,
    rpmLimit: 600,
    tpmLimit: 2_000_000,
    maxProjects: 50,
    maxMembers: 3,
    logRetentionDays: 90,
    features: [
      "Everything in Developer",
      "Priority routing",
      "Advanced analytics",
      "Fallback routing policies",
      "90-day log retention",
    ],
    available: false,
    sortOrder: 2,
  },
  {
    slug: "team",
    name: "Team",
    description: "Shared billing, projects and budgets for teams.",
    priceMonthlyCents: null,
    isPayAsYouGo: true,
    rpmLimit: 1_200,
    tpmLimit: 4_000_000,
    maxProjects: 200,
    maxMembers: 50,
    logRetentionDays: 90,
    features: [
      "Everything in Pro",
      "Multiple members and roles",
      "Team and project budgets",
      "Shared billing",
      "Audit logs",
    ],
    available: false,
    sortOrder: 3,
  },
  {
    slug: "enterprise",
    name: "Enterprise",
    description: "Custom contracts, dedicated infrastructure and controls.",
    priceMonthlyCents: null,
    isPayAsYouGo: false,
    rpmLimit: 6_000,
    tpmLimit: 20_000_000,
    maxProjects: 10_000,
    maxMembers: 10_000,
    logRetentionDays: 365,
    features: [
      "Custom pricing and committed spend",
      "SSO and advanced RBAC",
      "Dedicated deployments and private networking",
      "Data residency options",
      "SLA and named support",
    ],
    contactSales: true,
    sortOrder: 4,
  },
] as const;

export const FEATURE_FLAGS = [
  { key: "GPU_CLOUD_ENABLED", description: "GPU rental (not live — waitlist only)", enabled: false },
  { key: "MCP_ENABLED", description: "MCP server registry in the dashboard (preview)", enabled: true },
  { key: "AGENTS_ENABLED", description: "Agent builder (preview)", enabled: false },
  { key: "BYOK_ENABLED", description: "Bring-your-own provider keys", enabled: true },
  { key: "NEW_ROUTER_ENABLED", description: "Next-generation routing engine", enabled: false },
  { key: "BETA_MODELS_ENABLED", description: "Serve models in BETA status", enabled: false },
  { key: "WEBHOOKS_ENABLED", description: "Customer webhooks", enabled: true },
  { key: "SIGNUPS_ENABLED", description: "Allow new account registration", enabled: true },
] as const;
